[project]
name = "Truth_Check_Agent"
version = "0.1.0"
description = "AI_Truth_Check_Agent_CLI_Tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]

[project.scripts]
checker = "main:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
